FROM suilteam/cxy-base:alpine

RUN apk add --update --no-cache wget

# Setup cxy environment variables
ENV CXY_ROOT=/usr/local
ENV CXY_STDLIB_DIR="${CXY_ROOT}/lib/cxy/std"

# Install cxy compiler
RUN bash -c "$(wget https://raw.githubusercontent.com/dccarter/cstar/refs/heads/main/src/tools/download-cxy.sh -O -)"
