when:
  - event: pull_request
  - event: push
    branch: main

matrix:
  CXY_IMAGE:
    - alpine
    - ubuntu

steps:
  - name: build
    image: suilteam/cxy-dev:latest-${CXY_IMAGE}
    pull: true
    commands:
      - >-
        cmake -B $CI_WORKSPACE/build
        -DCMAKE_BUILD_TYPE=Debug
        -DLLVM_ROOT_DIR=`llvm-config --prefix`
        -DCMAKE_C_COMPILER=/usr/bin/clang
        -DCMAKE_CXX_COMPILER=/usr/bin/clang++
      - cmake --build $CI_WORKSPACE/build --config Debug

  - name: Compiler tests
    image: suilteam/cxy-dev:latest-${CXY_IMAGE}
    directory: ./build
    commands:
      - export LLVM_MAJOR_VERSION=`llvm-config --version | cut -d '.' -f 1`
      - FILE_CHECK=`llvm-config --prefix`/bin/FileCheck $CI_WORKSPACE/tests/runner.sh

  - name: Stdlib tests
    image: suilteam/cxy-dev:latest-${CXY_IMAGE}
    directory: ./build
    commands:
      - ctest --output-on-failure
