name: Cxy Alpine Base Image

on:
  push:
    branches:
      - main
    paths:
      - docker/Dockerfile.alpine

jobs:
  alpine-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile.alpine
          push: true
          tags: suilteam/cxy-base:alpine
