name: Cxy Ubuntu Image

on:
  push:
    tags: [ "v*.*.*" ]
    branches:
      - main
    paths:
      - docker/Dockerfile.ubuntu.cxy
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

jobs:
  ubuntu-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile.ubuntu.cxy
          push: true
          tags: suilteam/cxy:${{ env.IMAGE_TAG }}-ubuntu
          build-args: |
            "RELEASE_TAG=${{ github.ref_name }}"
