name: Cxy Ubuntu Dev Image

on:
  push:
    tags: [ "v*.*.*" ]
    branches:
      - main
    paths:
      - docker/Dockerfile.ubuntu.dev

env:
  IMAGE_TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

jobs:
  ubuntu-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile.ubuntu.dev
          push: true
          tags: suilteam/cxy-dev:${{env.IMAGE_TAG}}-ubuntu
